project:
  type: website

website:
  favicon: "images/NavBar_logo.png"
  navbar:
    logo: "images/NavBar_logo.png"
    
    right:
      - href: index.qmd
        text: Home
      - text: "Team"
        href: about.qmd
    left:
      - text: "Proposal"
        href: "Proposal/Proposal.html"

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual


