project:
  type: website

website:
  favicon: "images/Website_logo.png"
  back-to-top-navigation: true
  page-navigation: true
  sidebar:
    tools:
      - icon: github
        text: "Github"
        href: https://github.com/WYaling/ISSS608-VAA-Project
    logo: "images/hdbresale.png"
    style: "docked"
    search: true
    background: "#7986CB"
    foreground: light
    contents:
      - href: index.qmd
        text: Introduction
      - text: "Team"
        href: about.qmd
      - text: "Meeting Minutes"
        href: "Meeting_Minutes/Meeting_Minutes.html"
      - text: "Proposal"
        href: "Proposal/Proposal.html"

        

format:
  html:
    theme: lux
    css: styles.css
    mainfont: Arial
    fontsize: 1em
    toc: true
    linestretch: 1.5
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    grid:
      sidebar-width: 220px
      body-width: 960px
      margin-width: 220px
      gutter-width: 1.5rem




editor: visual


